name = "cyber-simulator"
compatibility_date = "2025-08-14"
main = "src/server/hono/app.ts"


[[d1_databases]]
binding = "DB" # must match what you use in code
database_name = "cyber_db"
database_id = "3a54e02d-9cc9-42d6-aa45-f6cc751d1ac4"

[dev]
port = 8787
